[project]
name = "streamlit-webrtc-ice-config-experiment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "streamlit>=1.43.2",
    "streamlit-webrtc>=0.53.3",
    "twilio>=9.5.0",
]
